(function(){
var qs=new URLSearchParams(location.search),VIDEO_ID=qs.get("v")||"y1NWwTHIgBA";
var LESSON={verbs:[
{inf:"sprechen",en:"to speak",note:"stem change e → i",start:30.05,forms:[["ich","spreche",30.05],["du","sprichst",31.23],["er / sie / es","spricht",32.40],["wir","sprechen",34.45],["ihr","sprecht",35.89],["sie / Sie","sprechen",38.97]],examples:[["Ich spreche Deutsch.","I speak German.",41.95],["Sprichst du Englisch?","Do you speak English?",43.71]]},
{inf:"sehen",en:"to see",note:"stem change e → ie",start:45.08,forms:[["ich","sehe",45.08],["du","siehst",46.23],["er / sie / es","sieht",47.31],["wir","sehen",49.65],["ihr","seht",50.75],["sie / Sie","sehen",52.27]],examples:[["Ich sehe dich.","I see you.",54.29],["Siehst du das?","Do you see that?",55.70]]},
{inf:"geben",en:"to give",note:"stem change e → i",start:85.45,forms:[["ich","gebe",85.45],["du","gibst",86.50],["er / sie / es","gibt",87.64],["wir","geben",90.10],["ihr","gebt",91.24],["sie / Sie","geben",93.95]],examples:[["Ich gebe dir das.","I give you that.",95.43],["Gibst du mir das?","Are you giving me that?",96.97]]},
{inf:"nehmen",en:"to take",note:"stem change e → i",start:99.29,forms:[["ich","nehme",99.29],["du","nimmst",100.41],["er / sie / es","nimmt",101.45],["wir","nehmen",103.85],["ihr","nehmt",104.95],["sie / Sie","nehmen",106.10]],examples:[["Ich nehme den Bus.","I take the bus.",108.49],["Nimmst du auch den Bus?","Do you also take the bus?",110.82]]},
{inf:"fahren",en:"to drive / travel",note:"stem change a → ä",start:113.63,forms:[["ich","fahre",113.63],["du","fährst",115.17],["er / sie / es","fährt",116.32],["wir","fahren",118.72],["ihr","fahrt",119.60],["sie / Sie","fahren",120.77]],examples:[["Ich fahre nach Hause.","I’m going home.",121.90],["Fährst du mit?","Are you coming along?",125.34]]}
]};
var modes={meaning:"Meaning",conjugation:"Conjugation",sentence:"Sentence completion",reverse:"Reverse recall",song:"Hear it in the song"};
var state={verb:0,mode:"conjugation",count:0,correct:0,answered:false,q:null,cardPool:[],cardIndex:0,cardDirection:"prompt-form"};
var key="rd-fuenf-verben-ein-rhythmus-v1",progress;
try{progress=JSON.parse(localStorage.getItem(key)||'{"mastered":{},"review":{},"attempts":0,"correct":0}')}catch(e){progress={mastered:{},review:{},attempts:0,correct:0}}
if(!progress.mastered)progress.mastered={};if(!progress.review)progress.review={};
function $(s){return document.querySelector(s)}function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function fmt(t){var m=Math.floor(t/60),s=t-m*60;return m+":"+String(s.toFixed(2)).padStart(5,"0")}
function yurl(t){return VIDEO_ID?"https://www.youtube.com/watch?v="+encodeURIComponent(VIDEO_ID)+"&t="+Math.max(0,Math.floor(t)-1)+"s":""}
function hear(t,label){var u=yurl(t),txt="▶ "+(label||"Hear in song")+" · "+fmt(t);return u?'<a class="hear hear-song" href="'+u+'" target="_blank" rel="noopener">'+txt+"</a>":'<span class="hear hear-song disabled">'+txt+"</span>"}
function speakControl(text,label){return '<button type="button" class="hear hear-german speak-control" data-speak="'+encodeURIComponent(text)+'">🔊 '+(label||"Hear German")+"</button>"}
function audioPair(text,t,label){return '<div class="audio-pair">'+speakControl(text)+hear(t,label)+"</div>"}
function save(){localStorage.setItem(key,JSON.stringify(progress));updateProgress()}function formKey(v,f){return v.inf+":"+f[0]}
function allCards(){var out=[];LESSON.verbs.forEach(function(v,vi){v.forms.forEach(function(f,fi){out.push({id:out.length+1,vi:vi,fi:fi,v:v,f:f,key:formKey(v,f)})})});return out}
function exampleFor(c){return c.v.examples[c.fi%c.v.examples.length]}
function renderVerbs(){var g=$("#verbGrid");g.innerHTML=LESSON.verbs.map(function(v,i){return '<button class="verbchip '+(i===state.verb?"active":"")+'" data-i="'+i+'"><strong>'+v.inf+"</strong><span>"+v.en+"</span></button>"}).join("");$$(".verbchip").forEach(function(b){b.onclick=function(){state.verb=+b.dataset.i;renderVerbs();renderLesson()}})}
function renderLesson(){var v=LESSON.verbs[state.verb];$("#lesson").innerHTML='<div class="lessontop"><div><h3 class="verbtitle">'+v.inf+'</h3><div class="meaning">'+v.en+" · <strong>"+v.note+"</strong></div></div>"+audioPair(v.inf,v.start,"Hear section")+'</div><div class="tablewrap"><table class="conj"><thead><tr><th>Person</th><th>Präsens</th><th>Audio</th></tr></thead><tbody>'+v.forms.map(function(f){return "<tr><td>"+f[0]+"</td><td>"+f[1]+"</td><td>"+audioPair(f[0]+" "+f[1],f[2])+"</td></tr>"}).join("")+'</tbody></table></div><div class="examples">'+v.examples.map(function(x){return '<div class="example"><div class="de">'+x[0]+'</div><div class="en">'+x[1]+'</div><div class="example-audio">'+audioPair(x[0],x[2])+"</div></div>"}).join("")+"</div>"}
function resetCardPool(){var filter=$("#cardVerbFilter").value;state.cardPool=allCards().filter(function(c){return filter==="all"||c.v.inf===filter});state.cardIndex=0;renderCard()}
function cardFrontBack(c){var d=state.cardDirection;if(d==="mixed")d=c.id%2?"prompt-form":"form-prompt";return d==="prompt-form"?{kick:"Conjugate",front:c.f[0]+" + "+c.v.inf,back:c.f[0]+" "+c.f[1]}:{kick:"Identify",front:c.f[0]+" "+c.f[1],back:c.f[0]+" + "+c.v.inf}}
function currentCard(){return state.cardPool[state.cardIndex]||allCards()[0]}
function renderCard(){var c=currentCard(),fb=cardFrontBack(c),ex=exampleFor(c),card=$("#flashcard");card.classList.remove("flipped");card.setAttribute("aria-pressed","false");$("#frontNumber").textContent=$("#backNumber").textContent=String(c.id).padStart(2,"0");$("#frontKicker").textContent=fb.kick;$("#frontPrompt").textContent=fb.front;$("#backAnswer").textContent=fb.back;$("#cardExampleDe").textContent=ex[0];$("#cardExampleEn").textContent=ex[1];$("#cardPosition").textContent=(state.cardIndex+1)+" / "+state.cardPool.length;$("#cardContext").textContent=c.v.inf+" · "+c.v.note;var u=yurl(c.f[2]),a=$("#songCard");a.textContent="▶ Hear it in the song · "+fmt(c.f[2]);a.href=u||"#";a.classList.toggle("disabled",!u)}
function nextCard(){state.cardIndex=(state.cardIndex+1)%state.cardPool.length;renderCard()}function prevCard(){state.cardIndex=(state.cardIndex-1+state.cardPool.length)%state.cardPool.length;renderCard()}
function shuffleCards(){for(var i=state.cardPool.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),tmp=state.cardPool[i];state.cardPool[i]=state.cardPool[j];state.cardPool[j]=tmp}state.cardIndex=0;renderCard()}
function markCard(type){var c=currentCard();if(type==="known"){progress.mastered[c.key]=1;delete progress.review[c.key]}else{progress.review[c.key]=1;delete progress.mastered[c.key]}save();nextCard()}
function speakGerman(text){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang="de-DE";u.rate=.82;window.speechSynthesis.speak(u)}
function forms(){var a=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){a.push({verb:v.inf,en:v.en,person:f[0],form:f[1],t:f[2],key:formKey(v,f)})})});return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return a.slice().sort(function(){return Math.random()-.5})}
function question(){var all=forms(),v=pick(LESSON.verbs),f=pick(v.forms),q="",correct="",alts=[],play=0;
if(state.mode==="meaning"){q='What does “'+v.inf+'” mean?';correct=v.en;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.en});f=null}
if(state.mode==="conjugation"){q=f[0]+" ____ ("+v.inf+")";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="sentence"){var ex=pick(v.examples),target=v.forms.find(function(x){return ex[0].toLowerCase().indexOf(x[1].toLowerCase())>-1})||f;f=target;q=ex[0].replace(new RegExp(target[1],"i"),"____");correct=target[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="reverse"){q='“'+f[1]+'” belongs to which infinitive?';correct=v.inf;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.inf})}
if(state.mode==="song"){q="At "+fmt(f[2])+", which form do you hear?";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form});play=f[2]}
var unique=Array.from(new Set(alts));return{q:q,correct:correct,answers:shuffle([correct].concat(shuffle(unique).slice(0,3))),v:v,f:f,play:play}}
function renderTabs(){$("#tabs").innerHTML=Object.keys(modes).map(function(k){return '<button class="tab '+(k===state.mode?"active":"")+'" data-mode="'+k+'">'+modes[k]+"</button>"}).join("");$$(".tab").forEach(function(b){b.onclick=function(){state.mode=b.dataset.mode;renderTabs();nextQuestion()}})}
function nextQuestion(){state.answered=false;state.q=question();state.count++;$("#qMode").textContent=modes[state.mode];$("#qCount").textContent="Question "+state.count;$("#question").innerHTML=state.q.q+(state.q.play?'<div style="margin-top:16px">'+hear(state.q.play,"Play this phrase")+"</div>":"");$("#answers").innerHTML=state.q.answers.map(function(a){return '<button class="answer" data-a="'+encodeURIComponent(a)+'">'+a+"</button>"}).join("");$("#feedback").textContent="";$("#nextBtn").disabled=true;$$(".answer").forEach(function(b){b.onclick=function(){answerQuestion(b,decodeURIComponent(b.dataset.a))}});score()}
function answerQuestion(btn,a){if(state.answered)return;state.answered=true;progress.attempts++;var ok=a===state.q.correct;if(ok){state.correct++;progress.correct++;btn.classList.add("correct");if(state.q.f){progress.mastered[formKey(state.q.v,state.q.f)]=1;delete progress.review[formKey(state.q.v,state.q.f)]}$("#feedback").textContent="Correct. Keep the pattern moving."}else{btn.classList.add("wrong");$$(".answer").forEach(function(x){if(decodeURIComponent(x.dataset.a)===state.q.correct)x.classList.add("correct")});if(state.q.f)progress.review[formKey(state.q.v,state.q.f)]=1;$("#feedback").textContent="Answer: "+state.q.correct}$$(".answer").forEach(function(x){x.disabled=true});$("#nextBtn").disabled=false;save();score()}
function score(){var done=state.count-(state.answered?0:1);$("#score").textContent="This session: "+state.correct+"/"+Math.max(0,done)}
function updateProgress(){var m=Math.min(30,Object.keys(progress.mastered).length);$("#mastered").textContent=m;$("#bar").style.width=(m/30*100)+"%";$("#progressLabel").textContent=m+" of 30 conjugation forms reinforced"}
function dl(name,text,type){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:type||"text/plain"}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function csv(){var rows=["verb,meaning,person,form,timestamp"];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push([v.inf,v.en,f[0],f[1],fmt(f[2])].map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(","))})});dl("fuenf-verben-ein-rhythmus-vol-2.csv",rows.join("\n"),"text/csv")}
function anki(){var rows=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push(f[0]+" "+v.inf+"\t"+f[0]+" "+f[1]+"\t"+v.en+" · "+fmt(f[2]))})});dl("fuenf-verben-ein-rhythmus-vol-2-anki.tsv",rows.join("\n"),"text/tab-separated-values")}
var swipeStartX=0,swipeStartY=0,suppress=false;
$("#flashcard").onclick=function(){if(suppress)return;var on=this.classList.toggle("flipped");this.setAttribute("aria-pressed",on?"true":"false")};
$("#flashcard").addEventListener("touchstart",function(e){if(e.touches&&e.touches.length){swipeStartX=e.touches[0].clientX;swipeStartY=e.touches[0].clientY}},{passive:true});
$("#flashcard").addEventListener("touchend",function(e){if(!e.changedTouches||!e.changedTouches.length)return;var dx=e.changedTouches[0].clientX-swipeStartX,dy=e.changedTouches[0].clientY-swipeStartY;if(Math.abs(dx)<50||Math.abs(dx)<=Math.abs(dy)*1.15)return;suppress=true;dx<0?nextCard():prevCard();setTimeout(function(){suppress=false},250)},{passive:true});
$("#cardVerbFilter").onchange=resetCardPool;$("#cardDirection").onchange=function(){state.cardDirection=this.value;renderCard()};$("#shuffleCards").onclick=shuffleCards;$("#nextCard").onclick=nextCard;$("#prevCard").onclick=prevCard;$("#knownCard").onclick=function(){markCard("known")};$("#reviewCard").onclick=function(){markCard("review")};$("#speakCard").onclick=function(){var c=currentCard();speakGerman(c.f[0]+" "+c.f[1])};
document.body.addEventListener("click",function(e){var b=e.target.closest(".speak-control");if(b)speakGerman(decodeURIComponent(b.dataset.speak))});
$("#nextBtn").onclick=nextQuestion;$("#csvBtn").onclick=csv;$("#ankiBtn").onclick=anki;$("#printBtn").onclick=function(){window.print()};$("#resetBtn").onclick=function(){if(confirm("Reset local practice progress for this lesson?")){progress={mastered:{},review:{},attempts:0,correct:0};save()}};
document.addEventListener("keydown",function(e){if(document.activeElement&&/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;if(e.code==="Space"){e.preventDefault();$("#flashcard").click()}else if(e.key==="ArrowRight")nextCard();else if(e.key==="ArrowLeft")prevCard();else if(e.key==="1")markCard("review");else if(e.key==="2")markCard("known")});
var footer=$("#footerSong");if(VIDEO_ID){footer.href="https://www.youtube.com/watch?v="+encodeURIComponent(VIDEO_ID);$("#videoNote").textContent="Direct YouTube timestamp jumps are active for this lesson."}else{footer.style.display="none"}
renderVerbs();renderLesson();state.cardPool=allCards();renderCard();renderTabs();nextQuestion();updateProgress();
})();