(function(){
var VIDEO_ID="YMZONJcQjhY";
var LESSON={verbs:[
{inf:"machen",en:"to do / make",note:"regular",start:18.460,forms:[["ich","mache",21.980],["du","machst",22.600],["er / sie / es","macht",23.380],["wir","machen",26.020],["ihr","macht",27.100],["sie / Sie","machen",27.620]],examples:[["Ich mache das heute.","I'm doing that today.",30.360],["Was machst du?","What are you doing?",32.180]]},
{inf:"gehen",en:"to go",note:"regular present pattern",start:35.920,forms:[["ich","gehe",37.130],["du","gehst",38.180],["er / sie / es","geht",38.880],["wir","gehen",40.820],["ihr","geht",41.340],["sie / Sie","gehen",41.840]],examples:[["Ich gehe nach Hause.","I'm going home.",44.060],["Gehst du mit?","Are you coming along?",45.400]]},
{inf:"kommen",en:"to come",note:"regular",start:89.220,forms:[["ich","komme",90.520],["du","kommst",92.100],["er / sie / es","kommt",92.720],["wir","kommen",93.640],["ihr","kommt",94.320],["sie / Sie","kommen",94.900]],examples:[["Ich komme morgen.","I'm coming tomorrow.",95.880],["Kommst du auch?","Are you coming too?",97.080]]},
{inf:"haben",en:"to have",note:"irregular: hast / hat",start:100.660,forms:[["ich","habe",102.210],["du","hast",103.070],["er / sie / es","hat",103.240],["wir","haben",104.780],["ihr","habt",105.380],["sie / Sie","haben",105.920]],examples:[["Ich habe Zeit.","I have time.",107.220],["Hast du Zeit?","Do you have time?",108.220]]},
{inf:"sein",en:"to be",note:"highly irregular",start:111.280,forms:[["ich","bin",112.380],["du","bist",112.920],["er / sie / es","ist",113.560],["wir","sind",114.660],["ihr","seid",115.100],["sie / Sie","sind",115.820]],examples:[["Ich bin hier.","I am here.",116.240],["Wir sind bereit.","We are ready.",118.300]]}
]};
var modes={meaning:"Meaning",conjugation:"Conjugation",sentence:"Sentence completion",reverse:"Reverse recall",song:"Hear it in the song"};
var state={verb:0,mode:"conjugation",count:0,correct:0,answered:false,q:null};
var key="rd-schritt-fuer-schritt-v3";
var progress;try{progress=JSON.parse(localStorage.getItem(key)||'{"mastered":{},"attempts":0,"correct":0}')}catch(e){progress={mastered:{},attempts:0,correct:0}}
function $(s){return document.querySelector(s)}function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function fmt(t){var m=Math.floor(t/60),s=t-m*60;return m+":"+String(s.toFixed(2)).padStart(5,"0")}
function yurl(t){return "https://www.youtube.com/watch?v="+VIDEO_ID+"&t="+Math.floor(t)+"s"}
function hear(t,label){return '<a class="hear" href="'+yurl(t)+'" target="_blank" rel="noopener">▶ '+(label||"Hear in song")+" · "+fmt(t)+"</a>"}
function renderFlipCards(){var g=$("#flipGrid");if(!g)return;g.innerHTML=LESSON.verbs.map(function(v,i){var sample=v.forms[1][0]+" "+v.forms[1][1];return '<div class="flipcard" tabindex="0" role="button" aria-pressed="false" aria-label="Flip card for '+v.inf+'"><div class="flipinner"><div class="flipface flipfront"><span class="fliphint">German verb</span><strong>'+v.inf+'</strong><span>'+v.en+'</span></div><div class="flipface flipback"><span class="fliphint">Recall</span><strong>'+sample+'</strong><span>'+v.note+'</span></div></div></div>'}).join("");$("#flipGrid .flipcard").forEach(function(card){function flip(){var on=card.classList.toggle("is-flipped");card.setAttribute("aria-pressed",on?"true":"false")}card.onclick=flip;card.onkeydown=function(e){if(e.key==="Enter"||e.key===" "){e.preventDefault();flip()}}})}\nfunction renderVerbs(){var g=$("#verbGrid");g.innerHTML=LESSON.verbs.map(function(v,i){return '<button class="verbchip '+(i===state.verb?"active":"")+'" data-i="'+i+'"><strong>'+v.inf+"</strong><span>"+v.en+"</span></button>"}).join("");$$(".verbchip").forEach(function(b){b.onclick=function(){state.verb=+b.dataset.i;renderVerbs();renderLesson()}})}
function renderLesson(){var v=LESSON.verbs[state.verb];$("#lesson").innerHTML='<div class="lessontop"><div><h3 class="verbtitle">'+v.inf+'</h3><div class="meaning">'+v.en+" · <strong>"+v.note+"</strong></div></div>"+hear(v.start,"Hear section")+'</div><div class="tablewrap"><table class="conj"><thead><tr><th>Person</th><th>Präsens</th><th>Song</th></tr></thead><tbody>'+v.forms.map(function(f){return "<tr><td>"+f[0]+"</td><td>"+f[1]+"</td><td>"+hear(f[2])+"</td></tr>"}).join("")+'</tbody></table></div><div class="examples">'+v.examples.map(function(x){return '<div class="example"><div class="de">'+x[0]+'</div><div class="en">'+x[1]+'</div><div style="margin-top:10px">'+hear(x[2],"Hear example")+"</div></div>"}).join("")+"</div>"}
function forms(){var a=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){a.push({verb:v.inf,en:v.en,person:f[0],form:f[1],t:f[2]})})});return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return a.slice().sort(function(){return Math.random()-.5})}
function question(){var all=forms(),v=pick(LESSON.verbs),f=pick(v.forms),q="",correct="",alts=[],play=0;
if(state.mode==="meaning"){q='What does “'+v.inf+'” mean?';correct=v.en;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.en});f=null}
if(state.mode==="conjugation"){q=f[0]+" ____ ("+v.inf+")";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="sentence"){var ex=pick(v.examples),target=v.forms.find(function(x){return ex[0].toLowerCase().indexOf(x[1].toLowerCase())>-1})||f;f=target;q=ex[0].replace(new RegExp(target[1],"i"),"____");correct=target[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="reverse"){q='“'+f[1]+'” belongs to which infinitive?';correct=v.inf;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.inf})}
if(state.mode==="song"){q="At "+fmt(f[2])+", which form do you hear?";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form});play=f[2]}
var unique=Array.from(new Set(alts));return{q:q,correct:correct,answers:shuffle([correct].concat(shuffle(unique).slice(0,3))),v:v,f:f,play:play}}
function renderTabs(){$("#tabs").innerHTML=Object.keys(modes).map(function(k){return '<button class="tab '+(k===state.mode?"active":"")+'" data-mode="'+k+'">'+modes[k]+"</button>"}).join("");$$(".tab").forEach(function(b){b.onclick=function(){state.mode=b.dataset.mode;renderTabs();next()}})}
function next(){state.answered=false;state.q=question();state.count++;$("#qMode").textContent=modes[state.mode];$("#qCount").textContent="Question "+state.count;$("#question").innerHTML=state.q.q+(state.q.play?'<div style="margin-top:16px">'+hear(state.q.play,"Play this phrase")+"</div>":"");$("#answers").innerHTML=state.q.answers.map(function(a){return '<button class="answer" data-a="'+encodeURIComponent(a)+'">'+a+"</button>"}).join("");$("#feedback").textContent="";$("#nextBtn").disabled=true;$$(".answer").forEach(function(b){b.onclick=function(){answer(b,decodeURIComponent(b.dataset.a))}});score()}
function answer(btn,a){if(state.answered)return;state.answered=true;progress.attempts++;var ok=a===state.q.correct;if(ok){state.correct++;progress.correct++;btn.classList.add("correct");if(state.q.f){var k=state.q.v.inf+":"+state.q.f[0];progress.mastered[k]=(progress.mastered[k]||0)+1}$("#feedback").textContent="Correct. Keep the pattern moving."}else{btn.classList.add("wrong");$$(".answer").forEach(function(x){if(decodeURIComponent(x.dataset.a)===state.q.correct)x.classList.add("correct")});$("#feedback").textContent="Answer: "+state.q.correct}$$(".answer").forEach(function(x){x.disabled=true});$("#nextBtn").disabled=false;localStorage.setItem(key,JSON.stringify(progress));updateProgress();score()}
function score(){var done=state.count-(state.answered?0:1);$("#score").textContent="This session: "+state.correct+"/"+Math.max(0,done)}
function updateProgress(){var m=Math.min(30,Object.keys(progress.mastered).filter(function(k){return progress.mastered[k]>0}).length);$("#mastered").textContent=m;$("#bar").style.width=(m/30*100)+"%";$("#progressLabel").textContent=m+" of 30 conjugation forms reinforced"}
function dl(name,text,type){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:type||"text/plain"}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function csv(){var rows=["verb,meaning,person,form,timestamp,youtube"];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push([v.inf,v.en,f[0],f[1],fmt(f[2]),yurl(f[2])].map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(","))})});dl("schritt-fuer-schritt-vol-1.csv",rows.join("\n"),"text/csv")}
function anki(){var rows=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push(f[0]+" "+v.inf+"\t"+f[0]+" "+f[1]+"\t"+v.en+" · "+fmt(f[2]))})});dl("schritt-fuer-schritt-vol-1-anki.tsv",rows.join("\n"),"text/tab-separated-values")}
$("#nextBtn").onclick=next;$("#csvBtn").onclick=csv;$("#ankiBtn").onclick=anki;$("#printBtn").onclick=function(){print()};$("#resetBtn").onclick=function(){if(confirm("Reset local practice progress for this lesson?")){progress={mastered:{},attempts:0,correct:0};localStorage.setItem(key,JSON.stringify(progress));updateProgress()}};
renderVerbs();renderFlipCards();renderLesson();renderTabs();next();updateProgress();
})();