(function(){
var LESSON={verbs:[
{inf:"sprechen",en:"to speak",note:"e → i",forms:[["ich","spreche",30.05],["du","sprichst",31.23],["er / sie / es","spricht",32.40],["wir","sprechen",34.45],["ihr","sprecht",35.89],["sie / Sie","sprechen",38.97]],examples:[["Ich spreche Deutsch.","I speak German."],["Sprichst du Englisch?","Do you speak English?"]]},
{inf:"sehen",en:"to see",note:"e → ie",forms:[["ich","sehe",45.08],["du","siehst",46.23],["er / sie / es","sieht",47.31],["wir","sehen",49.65],["ihr","seht",50.75],["sie / Sie","sehen",52.27]],examples:[["Ich sehe dich.","I see you."],["Siehst du das?","Do you see that?"]]},
{inf:"geben",en:"to give",note:"e → i",forms:[["ich","gebe",85.45],["du","gibst",86.50],["er / sie / es","gibt",87.64],["wir","geben",90.10],["ihr","gebt",91.24],["sie / Sie","geben",93.95]],examples:[["Ich gebe dir das.","I give you that."],["Gibst du mir das?","Are you giving me that?"]]},
{inf:"nehmen",en:"to take",note:"e → i",forms:[["ich","nehme",99.29],["du","nimmst",100.41],["er / sie / es","nimmt",101.45],["wir","nehmen",103.85],["ihr","nehmt",104.95],["sie / Sie","nehmen",106.10]],examples:[["Ich nehme den Bus.","I take the bus."],["Nimmst du auch den Bus?","Do you also take the bus?"]]},
{inf:"fahren",en:"to drive / travel",note:"a → ä",forms:[["ich","fahre",113.63],["du","fährst",115.17],["er / sie / es","fährt",116.32],["wir","fahren",118.72],["ihr","fahrt",119.60],["sie / Sie","fahren",120.77]],examples:[["Ich fahre nach Hause.","I am going home."],["Fährst du mit?","Are you coming along?"]]}
]};
var VIDEO=new URLSearchParams(location.search).get("v")||"";
var modes={meaning:"Meaning",conjugation:"Conjugation",sentence:"Sentence completion",reverse:"Reverse recall",song:"Hear it in the song"};
var state={verb:0,mode:"conjugation",count:0,correct:0,answered:false,q:null};
var key="rd-schritt-fuer-schritt-v1";
var progress;try{progress=JSON.parse(localStorage.getItem(key)||'{"mastered":{},"attempts":0,"correct":0}')}catch(e){progress={mastered:{},attempts:0,correct:0}}
function $(s){return document.querySelector(s)}function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function fmt(t){return Math.floor(t/60)+":"+String(Math.floor(t%60)).padStart(2,"0")}
function yurl(t){return VIDEO?"https://www.youtube.com/watch?v="+encodeURIComponent(VIDEO)+"&t="+Math.floor(t)+"s":""}
function hear(t,label){var u=yurl(t),txt="▶ "+(label||"Hear in song")+" · "+fmt(t);return u?'<a class="hear" href="'+u+'" target="_blank" rel="noopener">'+txt+"</a>":'<span class="hear disabled">▶ '+fmt(t)+"</span>"}
function renderVerbs(){var g=$("#verbGrid");g.innerHTML=LESSON.verbs.map(function(v,i){return '<button class="verbchip '+(i===state.verb?"active":"")+'" data-i="'+i+'"><strong>'+v.inf+"</strong><span>"+v.en+"</span></button>"}).join("");$$(".verbchip").forEach(function(b){b.onclick=function(){state.verb=+b.dataset.i;renderVerbs();renderLesson()}})}
function renderLesson(){var v=LESSON.verbs[state.verb];$("#lesson").innerHTML='<div class="lessontop"><div><h3 class="verbtitle">'+v.inf+'</h3><div class="meaning">'+v.en+" · stem change <strong>"+v.note+"</strong></div></div>"+hear(v.forms[0][2],"First appearance")+'</div><div class="tablewrap"><table class="conj"><thead><tr><th>Person</th><th>Präsens</th><th>Song</th></tr></thead><tbody>'+v.forms.map(function(f){return "<tr><td>"+f[0]+"</td><td>"+f[1]+"</td><td>"+hear(f[2])+"</td></tr>"}).join("")+'</tbody></table></div><div class="examples">'+v.examples.map(function(x){return '<div class="example"><div class="de">'+x[0]+'</div><div class="en">'+x[1]+"</div></div>"}).join("")+"</div>"}
function forms(){var a=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){a.push({verb:v.inf,en:v.en,person:f[0],form:f[1],t:f[2]})})});return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return a.slice().sort(function(){return Math.random()-.5})}
function question(){var all=forms(),v=pick(LESSON.verbs),f=pick(v.forms),q="",correct="",alts=[],play=0;
if(state.mode==="meaning"){q='What does “'+v.inf+'” mean?';correct=v.en;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.en});f=null}
if(state.mode==="conjugation"){q=f[0]+" ____ ("+v.inf+")";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="sentence"){var ex=pick(v.examples),target=v.forms.find(function(x){return ex[0].toLowerCase().indexOf(x[1].toLowerCase())>-1})||f;f=target;q=ex[0].replace(new RegExp(target[1],"i"),"____");correct=target[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="reverse"){q='“'+f[1]+'” belongs to which infinitive?';correct=v.inf;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.inf})}
if(state.mode==="song"){q="At "+fmt(f[2])+", which form appears in the song?";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form});play=f[2]}
var unique=Array.from(new Set(alts));return{q:q,correct:correct,answers:shuffle([correct].concat(shuffle(unique).slice(0,3))),v:v,f:f,play:play}}
function renderTabs(){$("#tabs").innerHTML=Object.keys(modes).map(function(k){return '<button class="tab '+(k===state.mode?"active":"")+'" data-mode="'+k+'">'+modes[k]+"</button>"}).join("");$$(".tab").forEach(function(b){b.onclick=function(){state.mode=b.dataset.mode;renderTabs();next()}})}
function next(){state.answered=false;state.q=question();state.count++;$("#qMode").textContent=modes[state.mode];$("#qCount").textContent="Question "+state.count;$("#question").innerHTML=state.q.q+(state.q.play?'<div style="margin-top:16px">'+hear(state.q.play,"Play this phrase")+"</div>":"");$("#answers").innerHTML=state.q.answers.map(function(a){return '<button class="answer" data-a="'+encodeURIComponent(a)+'">'+a+"</button>"}).join("");$("#feedback").textContent="";$("#nextBtn").disabled=true;$$(".answer").forEach(function(b){b.onclick=function(){answer(b,decodeURIComponent(b.dataset.a))}});score()}
function answer(btn,a){if(state.answered)return;state.answered=true;progress.attempts++;var ok=a===state.q.correct;if(ok){state.correct++;progress.correct++;btn.classList.add("correct");if(state.q.f){var k=state.q.v.inf+":"+state.q.f[0];progress.mastered[k]=(progress.mastered[k]||0)+1}$("#feedback").textContent="Correct. Keep the pattern moving."}else{btn.classList.add("wrong");$$(".answer").forEach(function(x){if(decodeURIComponent(x.dataset.a)===state.q.correct)x.classList.add("correct")});$("#feedback").textContent="Answer: "+state.q.correct}$$(".answer").forEach(function(x){x.disabled=true});$("#nextBtn").disabled=false;localStorage.setItem(key,JSON.stringify(progress));updateProgress();score()}
function score(){var done=state.count-(state.answered?0:1);$("#score").textContent="This session: "+state.correct+"/"+Math.max(0,done)}
function updateProgress(){var m=Math.min(30,Object.keys(progress.mastered).filter(function(k){return progress.mastered[k]>0}).length);$("#mastered").textContent=m;$("#bar").style.width=(m/30*100)+"%";$("#progressLabel").textContent=m+" of 30 conjugation forms reinforced"}
function dl(name,text,type){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:type||"text/plain"}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function csv(){var rows=["verb,meaning,person,form,timestamp"];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push([v.inf,v.en,f[0],f[1],fmt(f[2])].map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(","))})});dl("schritt-fuer-schritt-vol-1.csv",rows.join("\n"),"text/csv")}
function anki(){var rows=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push(f[0]+" "+v.inf+"\t"+f[0]+" "+f[1]+"\t"+v.en)})});dl("schritt-fuer-schritt-vol-1-anki.tsv",rows.join("\n"),"text/tab-separated-values")}
$("#nextBtn").onclick=next;$("#csvBtn").onclick=csv;$("#ankiBtn").onclick=anki;$("#printBtn").onclick=function(){print()};$("#resetBtn").onclick=function(){if(confirm("Reset local practice progress for this lesson?")){progress={mastered:{},attempts:0,correct:0};localStorage.setItem(key,JSON.stringify(progress));updateProgress()}};
if(!VIDEO)$("#songNote").classList.add("show");renderVerbs();renderLesson();renderTabs();next();updateProgress();
})();