(function(){
var LESSON={verbs:[
{inf:"machen",en:"to do / make",note:"regular",forms:[["ich","mache"],["du","machst"],["er / sie / es","macht"],["wir","machen"],["ihr","macht"],["sie / Sie","machen"]],examples:[["Ich mache das heute.","I'm doing that today."],["Was machst du?","What are you doing?"]]},
{inf:"gehen",en:"to go",note:"regular present pattern",forms:[["ich","gehe"],["du","gehst"],["er / sie / es","geht"],["wir","gehen"],["ihr","geht"],["sie / Sie","gehen"]],examples:[["Ich gehe nach Hause.","I'm going home."],["Gehst du mit?","Are you coming along?"]]},
{inf:"kommen",en:"to come",note:"regular",forms:[["ich","komme"],["du","kommst"],["er / sie / es","kommt"],["wir","kommen"],["ihr","kommt"],["sie / Sie","kommen"]],examples:[["Ich komme morgen.","I'm coming tomorrow."],["Kommst du auch?","Are you coming too?"]]},
{inf:"haben",en:"to have",note:"irregular: hast / hat",forms:[["ich","habe"],["du","hast"],["er / sie / es","hat"],["wir","haben"],["ihr","habt"],["sie / Sie","haben"]],examples:[["Ich habe Zeit.","I have time."],["Hast du Zeit?","Do you have time?"]]},
{inf:"sein",en:"to be",note:"highly irregular",forms:[["ich","bin"],["du","bist"],["er / sie / es","ist"],["wir","sind"],["ihr","seid"],["sie / Sie","sind"]],examples:[["Ich bin hier.","I am here."],["Wir sind bereit.","We are ready."]]}
],review:["Ich mache","ich gehe","Du machst","du gehst","Wir machen","wir gehen","Ich mache","ich gehe","ich komme","ich habe","ich bin","Du machst","du gehst","du kommst","du hast","du bist","Wir machen","wir gehen","wir kommen","wir haben","wir sind"]};
var modes={meaning:"Meaning",conjugation:"Conjugation",sentence:"Sentence completion",reverse:"Reverse recall",song:"Song recall"};
var state={verb:0,mode:"conjugation",count:0,correct:0,answered:false,q:null};
var key="rd-schritt-fuer-schritt-v2";
var progress;try{progress=JSON.parse(localStorage.getItem(key)||'{"mastered":{},"attempts":0,"correct":0}')}catch(e){progress={mastered:{},attempts:0,correct:0}}
function $(s){return document.querySelector(s)}function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function renderVerbs(){var g=$("#verbGrid");g.innerHTML=LESSON.verbs.map(function(v,i){return '<button class="verbchip '+(i===state.verb?"active":"")+'" data-i="'+i+'"><strong>'+v.inf+"</strong><span>"+v.en+"</span></button>"}).join("");$$(".verbchip").forEach(function(b){b.onclick=function(){state.verb=+b.dataset.i;renderVerbs();renderLesson()}})}
function renderLesson(){var v=LESSON.verbs[state.verb];$("#lesson").innerHTML='<div class="lessontop"><div><h3 class="verbtitle">'+v.inf+'</h3><div class="meaning">'+v.en+" · <strong>"+v.note+"</strong></div></div></div><div class="tablewrap"><table class="conj"><thead><tr><th>Person</th><th>Präsens</th></tr></thead><tbody>"+v.forms.map(function(f){return "<tr><td>"+f[0]+"</td><td>"+f[1]+"</td></tr>"}).join("")+'</tbody></table></div><div class="examples">'+v.examples.map(function(x){return '<div class="example"><div class="de">'+x[0]+'</div><div class="en">'+x[1]+"</div></div>"}).join("")+"</div>"}
function forms(){var a=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){a.push({verb:v.inf,en:v.en,person:f[0],form:f[1]})})});return a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}function shuffle(a){return a.slice().sort(function(){return Math.random()-.5})}
function badForms(f,v){var ending=["e","st","t","en","t","en"];var idx=v.forms.indexOf(f);var stem=v.inf.slice(0,-2);return Array.from(new Set([stem+ending[(idx+1)%6],stem+ending[(idx+2)%6],v.inf,f[1]+"e"])).filter(function(x){return x!==f[1]})}
function question(){var all=forms(),v=pick(LESSON.verbs),f=pick(v.forms),q="",correct="",alts=[];
if(state.mode==="meaning"){q='What does “'+v.inf+'” mean?';correct=v.en;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.en});f=null}
if(state.mode==="conjugation"){q=f[0]+" ____ ("+v.inf+")";correct=f[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="sentence"){var ex=pick(v.examples),target=v.forms.find(function(x){return ex[0].toLowerCase().indexOf(x[1].toLowerCase())>-1})||f;f=target;q=ex[0].replace(new RegExp(target[1],"i"),"____");correct=target[1];alts=all.filter(function(x){return x.form!==correct}).map(function(x){return x.form})}
if(state.mode==="reverse"){q='“'+f[1]+'” belongs to which infinitive?';correct=v.inf;alts=LESSON.verbs.filter(function(x){return x.inf!==v.inf}).map(function(x){return x.inf})}
if(state.mode==="song"){q='Complete the Vol. 1 line: '+f[0]+' ____';correct=f[1];alts=badForms(f,v)}
var unique=Array.from(new Set(alts));return{q:q,correct:correct,answers:shuffle([correct].concat(shuffle(unique).slice(0,3))),v:v,f:f}}
function renderTabs(){$("#tabs").innerHTML=Object.keys(modes).map(function(k){return '<button class="tab '+(k===state.mode?"active":"")+'" data-mode="'+k+'">'+modes[k]+"</button>"}).join("");$$(".tab").forEach(function(b){b.onclick=function(){state.mode=b.dataset.mode;renderTabs();next()}})}
function next(){state.answered=false;state.q=question();state.count++;$("#qMode").textContent=modes[state.mode];$("#qCount").textContent="Question "+state.count;$("#question").textContent=state.q.q;$("#answers").innerHTML=state.q.answers.map(function(a){return '<button class="answer" data-a="'+encodeURIComponent(a)+'">'+a+"</button>"}).join("");$("#feedback").textContent="";$("#nextBtn").disabled=true;$$(".answer").forEach(function(b){b.onclick=function(){answer(b,decodeURIComponent(b.dataset.a))}});score()}
function answer(btn,a){if(state.answered)return;state.answered=true;progress.attempts++;var ok=a===state.q.correct;if(ok){state.correct++;progress.correct++;btn.classList.add("correct");if(state.q.f){var k=state.q.v.inf+":"+state.q.f[0];progress.mastered[k]=(progress.mastered[k]||0)+1}$("#feedback").textContent="Correct. Keep the pattern moving."}else{btn.classList.add("wrong");$$(".answer").forEach(function(x){if(decodeURIComponent(x.dataset.a)===state.q.correct)x.classList.add("correct")});$("#feedback").textContent="Answer: "+state.q.correct}$$(".answer").forEach(function(x){x.disabled=true});$("#nextBtn").disabled=false;localStorage.setItem(key,JSON.stringify(progress));updateProgress();score()}
function score(){var done=state.count-(state.answered?0:1);$("#score").textContent="This session: "+state.correct+"/"+Math.max(0,done)}
function updateProgress(){var m=Math.min(30,Object.keys(progress.mastered).filter(function(k){return progress.mastered[k]>0}).length);$("#mastered").textContent=m;$("#bar").style.width=(m/30*100)+"%";$("#progressLabel").textContent=m+" of 30 conjugation forms reinforced"}
function dl(name,text,type){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:type||"text/plain"}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},500)}
function csv(){var rows=["verb,meaning,person,form"];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push([v.inf,v.en,f[0],f[1]].map(function(x){return '"'+String(x).replaceAll('"','""')+'"'}).join(","))})});dl("schritt-fuer-schritt-vol-1.csv",rows.join("\n"),"text/csv")}
function anki(){var rows=[];LESSON.verbs.forEach(function(v){v.forms.forEach(function(f){rows.push(f[0]+" "+v.inf+"\t"+f[0]+" "+f[1]+"\t"+v.en)})});dl("schritt-fuer-schritt-vol-1-anki.tsv",rows.join("\n"),"text/tab-separated-values")}
$("#nextBtn").onclick=next;$("#csvBtn").onclick=csv;$("#ankiBtn").onclick=anki;$("#printBtn").onclick=function(){print()};$("#resetBtn").onclick=function(){if(confirm("Reset local practice progress for this lesson?")){progress={mastered:{},attempts:0,correct:0};localStorage.setItem(key,JSON.stringify(progress));updateProgress()}};
renderVerbs();renderLesson();renderTabs();next();updateProgress();
})();